project-includes = [
    "src/**/*.py*",
    "src/**/*.ipynb",
    "tests/**/*.py",
]

# Exclude scripts from transports transports/*/scripts/*
project-excludes = [
    "src/**/transports/**/scripts/**/*.py",
    "src/uds/core/util/ldaputil_old.py",
]

# Let the type checker resolve `tests.utils.test` etc.
search-path = [
    "src",
    "tests",
    ".",
]

python-platform = "linux"

[errors]
missing-override-decorator = true

