line-length = 120
extend-exclude = [
    "samples",
    "src/uds/transports/*/scripts",
    "src/uds/migrations"
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-line-length = "dynamic"

[lint]
# B023 is bogus on ruff 0.16.3 at least
# B017 is blind exception.. even when you want to :)
# PLC0414 is a nonsense. Reexports are done by import alias as same name as imported
# TRY002 is for create your own exception class, but we want to use the base one for now
# S110 is try/except/pass, for now keep as is
# DTZ006 Is datetime without tz, but this is buggy beceuse we use "make_aware" from django...
ignore = [
    "I001",
    "BLE001",
    "B023",
    "B017",
    "PLC0414",
    "TRY002",
    "S110",
    "DTZ006"
]
# "I001" for sort order fix
# Use with a LOT OF CARE, some dependencies can break if reordered
# Should not , but does :)
fixable = [
    "F541",
    "F841",
    "UP006",
    "UP007",
    "UP008",
    "UP037",
    "UP032",
    "UP045",
    "SIM102",
    "SIM103",
    "SIM114",
    "SIM210",
    "S110",
    "F401",
    "FURB136",
    "TC005",
    "C401",
    "PIE790",
    "RUF100",
    "PLR2044",
]

[lint.per-file-ignores]
# This is an old compat module, so pickle on those old items can still work
"src/uds/core/util/AutoAttributes.py" = ["N999"]

[lint.isort]
force-single-line = true
known-first-party = ["src"]
lines-between-types = 1
no-lines-before = ["future", "standard-library"]
