# Generated by Django 6.0.5 on 2026-05-29 03:35

from django.db import migrations, models

from uds.core import consts
from uds.models.user_service import _create_default_token

from uds.migrations.upgraders_v5 import perform_upgrade, noop_reverse


class Migration(migrations.Migration):
    dependencies = [
        ("uds", "0050_transports"),
    ]

    operations = [
        migrations.AddField(
            model_name="userservice",
            name="token",
            field=models.CharField(
                max_length=consts.ticket.TICKET_LENGTH,
                default="",
            ),
        ),
        migrations.AlterField(
            model_name="userservice",
            name="token",
            field=models.CharField(
                max_length=consts.ticket.TICKET_LENGTH,
                default=_create_default_token,
                unique=True,
                db_index=True,
            ),
        ),
        migrations.RunPython(perform_upgrade, reverse_code=noop_reverse),
    ]
