# Generated by Django 6.0.5 on 2026-05-29 03:35
import typing

from django.db import migrations, models

from uds.core import consts
from uds.models.user_service import _create_default_token

from uds.migrations.upgraders_v5 import perform_upgrade, noop_reverse


def _backfill_tokens(apps: typing.Any, _schema_editor: typing.Any) -> None:
    """Backfill tokens for existing UserServices before adding unique constraint"""
    UserService = apps.get_model("uds", "UserService")
    for us in UserService.objects.filter(token=""):
        us.token = _create_default_token()
        us.save(update_fields=["token"])


def _noop(apps: typing.Any, _schema_editor: typing.Any) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("uds", "0050_transports"),
    ]

    operations = [
        migrations.AddField(
            model_name="userservice",
            name="token",
            field=models.CharField(
                max_length=consts.ticket.TICKET_LENGTH,
                default="",
            ),
        ),
        migrations.RunPython(_backfill_tokens, reverse_code=_noop),
        migrations.AlterField(
            model_name="userservice",
            name="token",
            field=models.CharField(
                max_length=consts.ticket.TICKET_LENGTH,
                default=_create_default_token,
                unique=True,
                db_index=True,
            ),
        ),
        migrations.RunPython(perform_upgrade, reverse_code=noop_reverse),
    ]
