# Generated by Django 6.0.5 on 2026-05-29 03:35

from django.db import migrations

from .upgraders_v5 import perform_upgrade, noop_reverse


class Migration(migrations.Migration):
    dependencies = [
        ("uds", "0050_transports"),
    ]

    operations = [
        migrations.RunPython(perform_upgrade, reverse_code=noop_reverse),
    ]
