# Generated by Django 6.0.5 on 2026-05-31 03:20

import uds.core.util.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uds", "0051_services_upgrade"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImmutableLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.BigIntegerField(editable=False, unique=True)),
                (
                    "stamp",
                    models.DateTimeField(
                        db_index=True,
                        default=uds.core.util.model.sql_now,
                        editable=False,
                    ),
                ),
                ("anchor", models.BooleanField(default=False, editable=False)),
                ("previous_hash", models.BinaryField(max_length=32)),
                ("data", models.BinaryField()),
                ("entry_hash", models.BinaryField(max_length=32, unique=True)),
            ],
            options={
                "verbose_name": "Immutable Log Entry",
                "verbose_name_plural": "Immutable Log Entries",
                "db_table": "uds_immutable_log",
                "ordering": ["sequence"],
                "get_latest_by": "sequence",
            },
        ),
    ]
