# Generated by Django 6.1 on 2026-08-31.

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add optional hashed credentials for user REST/MCP access."""

    dependencies = [  # noqa: RUF012
        ("uds", "0052_immutablelog_remove_scheduler_frecuency"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="user",
            name="token_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
