# Generated by Django 6.1.1 on 2026-09-08 13:07
# Squash of the flow migrations: final schema in one step. All the
# dynamic data (CAS snapshots, review cache) lives on Properties, not on
# columns. Status choices are a callable reference (FlowStatus.as_choices):
# enum changes no longer generate migrations.

import django.db.models.deletion
import typing
import uds.core.types.mcp
import uds.core.util.model
import uds.core.util.properties
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uds", "0053_user_token_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionFlow",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "uuid",
                    models.CharField(default=uds.core.util.model.generate_uuid, max_length=50, unique=True),
                ),
                ("name", models.CharField(default="", max_length=128)),
                ("justification", models.TextField(default="")),
                (
                    "status",
                    models.CharField(
                        choices=typing.cast(typing.Any, uds.core.types.mcp.FlowStatus.as_choices),
                        db_index=True,
                        default=uds.core.types.mcp.FlowStatus["PENDING"],
                        max_length=16,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("due_date", models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ("created", models.DateTimeField(blank=True, default=uds.core.util.model.sql_now)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_action_flows",
                        to="uds.user",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_flows",
                        to="uds.user",
                    ),
                ),
            ],
            options={
                "db_table": "uds_action_flow",
            },
            bases=(models.Model, uds.core.util.properties.PropertiesMixin),
        ),
        migrations.CreateModel(
            name="FlowAction",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "uuid",
                    models.CharField(default=uds.core.util.model.generate_uuid, max_length=50, unique=True),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("action_type", models.CharField(default="", max_length=64)),
                ("target_kind", models.CharField(db_index=True, default="", max_length=32)),
                ("target_uuid", models.CharField(db_index=True, default="", max_length=50)),
                ("justification", models.TextField(default="")),
                ("values", models.JSONField(blank=True, default=None, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=typing.cast(typing.Any, uds.core.types.mcp.FlowActionStatus.as_choices),
                        db_index=True,
                        default=uds.core.types.mcp.FlowActionStatus["PENDING"],
                        max_length=16,
                    ),
                ),
                ("created", models.DateTimeField(blank=True, default=uds.core.util.model.sql_now)),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="uds.actionflow"
                    ),
                ),
            ],
            options={
                "db_table": "uds_flow_action",
                "constraints": [models.UniqueConstraint(fields=("flow", "order"), name="u_flwact_flow_order")],
            },
            bases=(models.Model, uds.core.util.properties.PropertiesMixin),
        ),
    ]
