# Generated by Django 6.1.1 on 2026-09-08 18:39

import uds.core.util.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uds", "0054_actionflow_flowaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionflow",
            name="created",
            field=models.DateTimeField(blank=True, default=uds.core.util.model.sql_now),
        ),
        migrations.AlterField(
            model_name="flowaction",
            name="created",
            field=models.DateTimeField(blank=True, default=uds.core.util.model.sql_now),
        ),
    ]
