"""Tests for the MetaPools REST handler.

Covers ``set_fallback_access`` / ``get_fallback_access`` custom methods
declared in :mod:`uds.REST.methods.meta_pools`.

Notes
-----
The custom-method URL is generated by the framework from the snake_case
method name: ``/metapools/<id>/set_fallback_access`` and
``/metapools/<id>/get_fallback_access``.

The ``set_fallback_access`` POST body uses the snake_case key
``fallback_access`` (matching the openapi schema). The Django model field
``MetaPool.fallbackAccess`` (camelCase) is intentionally kept as-is because
it is a persisted DB column and changing it would require a migration.
The mapping is done at the handler boundary only.

These tests are pinned to the current behaviour of ``meta_pools.py`` (the
REST handler was migrated to snake_case in the dataclass field, schema key
and ``get_item`` kwarg, while preserving the underlying model attribute).
"""

from __future__ import annotations

import typing

from uds.core.types.states import State
from uds import models

from tests.fixtures import services as services_fixtures
from tests.utils import rest


class MetaPoolTest(rest.test.RESTTestCase):
    @typing.override
    def setUp(self) -> None:
        # Override number of items to create
        super().setUp()
        self.login()

    def _create_pool_for_fallback_tests(self) -> models.MetaPool:
        """Create a real MetaPool via test fixtures (no REST roundtrip).

        The pool is created with one ServicePool member so it is a valid
        meta-pool candidate for the custom method calls.
        """
        service = services_fixtures.create_db_service(self.provider)
        osmanager = services_fixtures.create_db_osmanager()
        transport = services_fixtures.create_db_transport()
        pool = services_fixtures.create_db_servicepool(service, osmanager, self.groups, [transport])
        return services_fixtures.create_db_metapool(
            service_pools=[pool],
            groups=self.groups,
        )

    def _pool_count_in_db(self) -> int:
        return models.MetaPool.objects.all().count()

    # ------------------------------------------------------------------
    # Existing tests (preserved from before the CRUD extension)
    # ------------------------------------------------------------------
    def test_invalid_metapool(self) -> None:
        url = "metapools/INVALID/overview"
        response = self.client.rest_get(url)
        self.assertEqual(response.status_code, 404)

    def test_meta_pools(self) -> None:
        url = "metapools/overview"
        # Now, work
        response = self.client.rest_get(url)
        self.assertEqual(response.status_code, 200)

        # Get list of meta pools in db
        db_pools_len = models.MetaPool.objects.all().count()
        re_pools: list[dict[str, typing.Any]] = response.json()
        self.assertIsInstance(re_pools, list)
        self.assertEqual(db_pools_len, len(re_pools))

    def test_delete_removes_meta_pool(self) -> None:
        """DELETE /metapools/<id> removes the MetaPool."""
        pool = self._create_pool_for_fallback_tests()
        before = self._pool_count_in_db()
        response = self.client.rest_delete(f"metapools/{pool.uuid}")
        self.assertEqual(response.status_code, 200, response.content)
        self.assertEqual(self._pool_count_in_db(), before - 1)

    # ------------------------------------------------------------------
    # Custom-method coverage: fallback_access (GET reads, POST writes)
    # ------------------------------------------------------------------
    def test_get_fallback_access_default_is_allow(self) -> None:
        """GET /metapools/<id>/fallback_access on a fresh pool returns ALLOW.

        ``models.MetaPool.fallbackAccess`` defaults to ``State.ALLOW``.
        """
        pool = self._create_pool_for_fallback_tests()
        response = self.client.rest_get(f"metapools/{pool.uuid}/fallback_access")
        self.assertEqual(response.status_code, 200, response.content)
        self.assertEqual(response.json(), State.ALLOW)

    def test_post_fallback_access_snake_case(self) -> None:
        """POST /metapools/<id>/fallback_access with snake_case body key.

        Mirrors what the admin GUI sends (see
        ``gui/admin/src/app/types/rest.ts`` and the
        ``meta-pools-detail.component.ts`` consumer after the
        ``fallbackAccess`` -> ``fallback_access`` migration).
        """
        pool = self._create_pool_for_fallback_tests()
        response = self.client.rest_post(
            f"metapools/{pool.uuid}/fallback_access",
            data={"fallback_access": State.DENY},
        )
        self.assertEqual(response.status_code, 200, response.content)
        self.assertEqual(response.json(), State.DENY)

        # Persisted in model (DB row) - not only echoed in response.
        pool.refresh_from_db()
        self.assertEqual(pool.fallbackAccess, State.DENY)

        # GET fallback_access now reports the new value.
        get_resp = self.client.rest_get(f"metapools/{pool.uuid}/fallback_access")
        self.assertEqual(get_resp.status_code, 200, get_resp.content)
        self.assertEqual(get_resp.json(), State.DENY)

    def test_post_fallback_access_is_idempotent(self) -> None:
        """Calling POST fallback_access repeatedly with the same value is a no-op.

        Five POSTs with the same target value must end up with exactly one
        logical row in DB (pool count unchanged) and the same final value.
        """
        pool = self._create_pool_for_fallback_tests()
        pool_count_before = models.MetaPool.objects.count()

        for _ in range(5):
            resp = self.client.rest_post(
                f"metapools/{pool.uuid}/fallback_access",
                data={"fallback_access": State.DENY},
            )
            self.assertEqual(resp.status_code, 200, resp.content)
            self.assertEqual(resp.json(), State.DENY)

        # No extra MetaPool rows were created.
        self.assertEqual(models.MetaPool.objects.count(), pool_count_before)
        pool.refresh_from_db()
        self.assertEqual(pool.fallbackAccess, State.DENY)

    def test_post_fallback_access_round_trip_allow_to_deny(self) -> None:
        """Round-trip DENY -> ALLOW leaves the pool in ALLOW state."""
        pool = self._create_pool_for_fallback_tests()

        # First deny.
        deny = self.client.rest_post(
            f"metapools/{pool.uuid}/fallback_access",
            data={"fallback_access": State.DENY},
        )
        self.assertEqual(deny.status_code, 200, deny.content)
        self.assertEqual(deny.json(), State.DENY)

        # Then allow.
        allow = self.client.rest_post(
            f"metapools/{pool.uuid}/fallback_access",
            data={"fallback_access": State.ALLOW},
        )
        self.assertEqual(allow.status_code, 200, allow.content)
        self.assertEqual(allow.json(), State.ALLOW)

        pool.refresh_from_db()
        self.assertEqual(pool.fallbackAccess, State.ALLOW)
